### ISSUE TITLE
README 'Run' needs full URL for git clone

### ISSUE THREAD

**Issue by maxlcummins** [phiweger/uv#2]
Hiya,

Thanks a million for writing this up! I am very keen to give it a try today.

Just a heads up that the following line in your README 'Run' step reads:

``` git clone github.com/phiweger/uv.git ```

It fails, as it needs the full URL:

``` git clone https://github.com/phiweger/uv.git ```

Obviously not much of a barrier for people but thought I'd throw it in here.

Cheers

**Comment by phiweger** [comment]
thx for catching this! fixed.
